### PR TITLE
add tests

### PR DESCRIPTION
**Pull request by edouard-lopez**

### CODE REVIEW

**Comment by edouard-lopez** [comment]
bump, could you please merge or close the issue?

**Comment by edouard-lopez** [comment]
@herrbischoff any chance of merging this PR?

**Comment by herrbischoff** [comment]
Sorry, I have somehow lost interest in several projects for the time being, including this one. Would you be open to be added as a collaborator, helping me maintain and extend it?

**Comment by edouard-lopez** [comment]
Sure, I can help you merge PRs and stuff from time to time but extends it as I'm already contributing to others projects.

**Comment by herrbischoff** [comment]
I have just added you as a collaborator. Thanks for helping out!

**Pull request merged**
